#18subregion names and others
country_dictTest = {
            "Western europe": ["deu","nld","aut","bel","fra"],
            "Western Asia":["tur","irq","jor","lbn", "syr"], 
            "Northern Europe": ["gbr","nor","irl","swe","lva"]
             }

country_dict= {"Australia" : ["aus","cxr", "cck", "hmd", "nzl", "nfk"],
            #"antarctica" : ["ata"],
            "Eastern_Asia":["chn", "hkg", "mac", "prk", "jpn", "mng", "kor"],
            "Central_Asia":["kaz","kgz","tjk","tkm","uzb"],
            "Western_Asia":["tur","irq","jor","lbn", "syr"],
            "Southern_Asia":["afg","ind","irn","pak","bgd","btn","npl", "mdv","lka"],
            "Southern-Eastern_Asia":["phl","vnm""brn","khm","idn","lao","mys","mmr","sgp","tha","tls"],
            "Micronesia": ["gum","kir","mhl","fsm","nru","mnp","plw","umi"],
            "Malanesia":["fji","png","slb","vut"], # "ncl",
            "Polynesia": ["asm","cok","pyf","niu","pcn","wsm","tkl","ton","tuv","wlf"],
            "Latin_America_and_the_Caribbean": ["aia","atg","abw","bhs","brb","bes","vgb","cym","cub","cuw","dma","dom","grd","glp","hti","jam","mtq","msr","pri","blm","kna","lca",
                "maf","vct","sxm","tto","tca","vir","blz","cri","slv","gtm","hnd","mex","nic","pan","arg","bol","bvt","bra","chl","col","ecu","flk","guf","guy","pry","per","sgs",
                "sur","ury","ven"],
            "Northern_America":["bmu","can","grl","spm","usa"],
            "Eastern_Europe":["pol", "blr","bgr","cze","hun","mda","rou","rus","svk","ukr"],
            "Southern_Europe":["bih","mkd","alb","and","hrv","gib","grc","vat","mlt","mne","prt","ita","smr","srb","svn","esp"],
            "Northern_Africa":["mar","dza","egy","lby","sdn","tun","esh"],
            "Sub-Saharan_Africa":["cmr","som","nga","sen", "iot","bdi","com","dji","eri","eth","atf","ken","mdg","mwi","mus","myt","moz","reu","rwa","syc","ssd","uga","tza","zmb","zwe",
                "ago","caf","tcd","cog","cod","gnq","gab","stp","bwa","swz","lso","nam","zaf","ben","bfa","cpv","civ","gmb","gha","gin","gnb","lbr","mli","mrt","ner","shn","sle","tgo"],
            "Western_Europe": ["deu","nld","aut","bel","fra","lie","lux","mco","che"],
            "Northern_Europe": ["gbr","nor","irl","swe","lva","est","isl","sjm","fro","fin","jey","imn","ltu","dnk","ggy","ala"], 
            "Others": ["ocean","twn","unk","othe","urs","otham","yug","othaf","cenam","nstd","othme","othas","scg","tch","othna","sta"] }

country_dictW = {"Australia" : ["aus","cxr", "cck", "hmd", "nzl", "nfk"],
            #"antarctica" : ["ata"],
            "Eastern_Asia":["chn", "hkg", "mac", "prk", "jpn", "mng", "kor"],
            "Central_Asia":["kaz","kgz","tjk","tkm","uzb"],
            "Western_Asia":["tur","irq","jor","lbn", "syr"],
            "Southern_Asia":["afg","ind","irn","pak","bgd","btn","npl", "mdv","lka"],
            "Southern-Eastern_Asia":["phl","vnm""brn","khm","idn","lao","mys","mmr","sgp","tha","tls"],
            "Micronesia": ["gum","kir","mhl","fsm","nru","mnp","plw","umi"],
            "Malanesia":["fji","png","slb","vut"], # "ncl",
            "Polynesia": ["asm","cok","pyf","niu","pcn","wsm","tkl","ton","tuv","wlf"],
            "Latin_America_and_the_Caribbean": ["aia","atg","abw","bhs","brb","bes","vgb","cym","cub","cuw","dma","dom","grd","glp","hti","jam","mtq","msr","pri","blm","kna","lca",
                "maf","vct","sxm","tto","tca","vir","blz","cri","slv","gtm","hnd","mex","nic","pan","arg","bol","bvt","bra","chl","col","ecu","flk","guf","guy","pry","per","sgs",
                "sur","ury","ven"],
            "Northern_America":["bmu","can","grl","spm","usa"],
            "Eastern_Europe":["pol", "blr","bgr","cze","hun","mda","rou","rus","svk","ukr"],
            "Southern_Europe":["bih","mkd","alb","and","hrv","gib","grc","vat","mlt","mne","prt","ita","smr","srb","svn","esp"],
            "Northern_Africa":["mar","dza","egy","lby","sdn","tun","esh"],
            "Sub-Saharan_Africa":["cmr","som","nga","sen", "iot","bdi","com","dji","eri","eth","atf","ken","mdg","mwi","mus","myt","moz","reu","rwa","syc","ssd","uga","tza","zmb","zwe",
                "ago","caf","tcd","cog","cod","gnq","gab","stp","bwa","swz","lso","nam","zaf","ben","bfa","cpv","civ","gmb","gha","gin","gnb","lbr","mli","mrt","ner","shn","sle","tgo"],
            "Western_Europe": ["deu","nld","aut","bel","fra","lie","lux","mco","che"],
            "Northern_Europe": ["gbr","nor","irl","swe","lva","est","isl","sjm","fro","fin","jey","imn","ltu","ggy","ala"], #"dnk",
            "Northern_Europe_DNK": ["gbr","nor","irl","swe","lva","est","isl","sjm","fro","fin","jey","imn","ltu","dnk","ggy","ala"], # WITH dnk
            "Others": ["ocean","twn","unk","othe","urs","otham","yug","othaf","cenam","nstd","othme","othas","scg","tch","othna","sta"] }

country_dictCorrection = {"Oceania" : ["ocean","aus","cxr", "cck", "hmd", "nzl", "nfk","gum","kir","mhl","fsm","nru","mnp","plw","umi","fji","png","slb","vut","asm","cok","pyf","niu","pcn","wsm","tkl","ton","tuv","wlf",],
            "Eastern_Asia":["chn", "hkg", "mac", "prk", "jpn", "mng", "kor", "twn"],
            "Central_Asia":["kaz","kgz","tjk","tkm","uzb"],
            "Western_Asia":["tur","irq","jor","lbn", "syr"],
            "Southern_Asia":["afg","ind","irn","pak","bgd","btn","npl", "mdv","lka"],
            "Southern-Eastern_Asia":["phl","vnm""brn","khm","idn","lao","mys","mmr","sgp","tha","tls"],
            "Latin_America_and_the_Caribbean": ["aia","atg","abw","bhs","brb","bes","vgb","cym","cub","cuw","dma","dom","grd","glp","hti","jam","mtq","msr","pri","blm","kna","lca",
                "maf","vct","sxm","tto","tca","vir","blz","cri","slv","gtm","hnd","mex","nic","pan","arg","bol","bvt","bra","chl","col","ecu","flk","guf","guy","pry","per","sgs",
                "sur","ury","ven"],
            "Northern_America":["bmu","can","grl","spm","usa"],
            "Eastern_Europe":["pol", "blr","bgr","cze","hun","mda","rou","rus","svk","ukr"],
            "Southern_Europe":["bih","mkd","alb","and","hrv","gib","grc","vat","mlt","mne","prt","ita","smr","srb","svn","esp"],
            "Northern_Africa":["mar","dza","egy","lby","sdn","tun","esh"],
            "Sub-Saharan_Africa":["cmr","som","nga","sen", "iot","bdi","com","dji","eri","eth","atf","ken","mdg","mwi","mus","myt","moz","reu","rwa","syc","ssd","uga","tza","zmb","zwe",
                "ago","caf","tcd","cog","cod","gnq","gab","stp","bwa","swz","lso","nam","zaf","ben","bfa","cpv","civ","gmb","gha","gin","gnb","lbr","mli","mrt","ner","shn","sle","tgo"],
            "Western_Europe": ["deu","nld","aut","bel","fra","lie","lux","mco","che"],
            "Northern_Europe": ["gbr","nor","irl","swe","lva","est","isl","sjm","fro","fin","jey","imn","ltu","ggy","ala"], #"dnk",
            #"Denmark": ["dnk"], # WITH dnk
            "Others": ["unk","othe","urs","otham","yug","othaf","cenam","nstd","othme","othas","scg","tch","othna","sta"] }