country_dictEurope = {  "Europe":["gbr","nor","irl","swe","lva","est","isl","sjm","fro","fin","jey","imn","ltu","ggy","ala","dnk",
                                    "deu","nld","aut","bel","fra","lie","lux","mco","che",
                                     "blr","bgr","cze","hun","mda","rou","rus","svk","ukr",
                                     "bih","mkd","alb","and","hrv","gib","grc","vat","mlt","mne","prt","ita","smr","srb","svn","esp" ],#"pol",
                        "EUwithPol": ["lie","nor", "isl","che",
                                    "gbr",
                                    "bgr","cze","hun","rou","svk","dnk","est","fin","irl","cyp",
                                    "swe","lva","hrv","grc","ita","mlt","prt","svn","esp","aut",
                                    "bel","fra","deu","lux","mco","nld", "pol"],
                        "EuropeEU": ["lie","nor", "isl","che",
                                    "gbr",
                                    "bgr","cze","hun","rou","svk","dnk","est","fin","irl","cyp",
                                    "swe","lva","hrv","grc","ita","mlt","prt","svn","esp","aut",
                                    "bel","fra","deu","lux","mco","nld"],
                        
                        "EuropeNotEU": [ "blr","mda","rus", "ukr", "ala", "ggy", "jey", "fro", "imn","sjm",
                                    "alb", "and", "bih", "gib", "vat", "mne", "mkd", "smr", "srb"],
                        
                        "OutsideEurope": ["aus","cxr", "cck", "hmd", "nzl", "nfk","gum","kir","mhl","fsm",
                                    "nru","mnp","plw","umi","fji","png","slb","vut","asm","cok",    
                                    "pyf","niu","pcn","wsm","tkl","ton","tuv","wlf",
                                    
                                    "chn", "hkg", "mac", "prk", "jpn", "mng", "kor", "twn",
                                    "kaz","kgz","tjk","tkm","uzb",
                                    "tur","irq","jor","lbn", "syr", "are", "arm","aze", "bhr","geo", 
                                    "isr","kwt","omn","pse","qat","sau","yem",
                                    
                                    "afg","ind","irn","pak","bgd","btn","npl", "mdv","lka",
                                    "phl","vnm","brn","khm","idn","lao","mys","mmr","sgp","tha","tls", 

                                    "mar","dza","egy","lby","sdn","tun","esh","cmr","som","nga",
                                    "sen", "iot","bdi","com","dji","eri","eth","atf","ken","mdg",
                                    "mwi","mus","myt","moz","reu","rwa","syc","ssd","uga","tza",
                                    "zmb","zwe","ago","caf","tcd","cog","cod","gnq","gab","stp",
                                    "bwa","swz","lso","nam","zaf","ben","bfa","cpv","civ","gmb",
                                    "gha","gin","gnb","lbr","mli","mrt","ner","shn","sle","tgo",

                                    "aia","atg","abw","bhs","brb","bes","vgb","cym","cub","cuw",
                                    "dma","dom","grd","glp","hti","jam","mtq","msr","pri","blm",
                                    "kna","lca","maf","vct","sxm","tto","tca","vir","blz","cri",
                                    "slv","gtm","hnd","mex","nic","pan","arg","bol","bvt","bra",
                                    "chl","col","ecu","flk","guf","guy","pry","per","sgs","sur",
                                    "ury","ven",
                                    "bmu","can","grl","spm","usa"
                                    ],

                        "Oceania" : ["aus","cxr", "cck", "hmd", "nzl", "nfk","gum","kir","mhl","fsm",
                                    "nru","mnp","plw","umi","fji","png","slb","vut","asm","cok",    
                                    "pyf","niu","pcn","wsm","tkl","ton","tuv","wlf", "ncl"],
                        
                        "Asia":["chn", "hkg", "mac", "prk", "jpn", "mng", "kor", "twn",
                                "kaz","kgz","tjk","tkm","uzb",
                                "tur","irq","jor","lbn", "syr", "are", "arm","aze", "bhr","geo",
                                "isr","kwt", "omn","pse","qat","sau","yem",
                                "afg","ind","irn","pak","bgd","btn","npl", "mdv","lka",
                                "phl","vnm","brn","khm","idn","lao","mys","mmr","sgp","tha","tls"],

                        "Eastern_Asia":["chn", "hkg", "mac", "prk", "jpn", "mng", "kor", "twn"],
                        "Central_Asia":["kaz","kgz","tjk","tkm","uzb"],
                        "Western_Asia":["tur","irq","jor","lbn", "syr", "are", "arm", "aze", "bhr","geo",
                                        "isr","kwt", "omn","pse","qat","sau","yem"],
                        "Southern_Asia":["afg","ind","irn","pak","bgd","btn","npl", "mdv","lka"],
                        "Southern-Eastern_Asia":["phl","vnm","brn","khm","idn","lao","mys","mmr","sgp","tha","tls"],
                        
                        "Antarctica" :["ata"],
                        "Africa":   ["mar","dza","egy","lby","sdn","tun","esh","cmr","som","nga",
                                    "sen", "iot","bdi","com","dji","eri","eth","atf","ken","mdg",
                                    "mwi","mus","myt","moz","reu","rwa","syc","ssd","uga","tza",
                                    "zmb","zwe","ago","caf","tcd","cog","cod","gnq","gab","stp",
                                    "bwa","swz","lso","nam","zaf","ben","bfa","cpv","civ","gmb",
                                    "gha","gin","gnb","lbr","mli","mrt","ner","shn","sle","tgo"],

                        "Northern_Africa":["mar","dza","egy","lby","sdn","tun","esh"],
                        "Sub-Saharan_Africa":["cmr","som","nga","sen", "iot","bdi","com","dji","eri","eth",
                                            "atf","ken","mdg","mwi","mus","myt","moz","reu","rwa","syc",
                                            "ssd","uga","tza","zmb","zwe","ago","caf","tcd","cog","cod",
                                            "gnq","gab","stp","bwa","swz","lso","nam","zaf","ben","bfa",
                                            "cpv","civ","gmb","gha","gin","gnb","lbr","mli","mrt","ner",
                                            "shn","sle","tgo"],
                        
                        "America": ["aia","atg","abw","bhs","brb","bes","vgb","cym","cub","cuw",
                                    "dma","dom","grd","glp","hti","jam","mtq","msr","pri","blm",
                                    "kna","lca","maf","vct","sxm","tto","tca","vir","blz","cri",
                                    "slv","gtm","hnd","mex","nic","pan","arg","bol","bvt","bra",
                                    "chl","col","ecu","flk","guf","guy","pry","per","sgs","sur",
                                    "ury","ven",
                                    "bmu","can","grl","spm","usa"],

                        "Latin_America_and_the_Caribbean": ["aia","atg","abw","bhs","brb","bes","vgb","cym","cub","cuw",
                                                            "dma","dom","grd","glp","hti","jam","mtq","msr","pri","blm",
                                                            "kna","lca","maf","vct","sxm","tto","tca","vir","blz","cri",
                                                            "slv","gtm","hnd","mex","nic","pan","arg","bol","bvt","bra",
                                                            "chl","col","ecu","flk","guf","guy","pry","per","sgs","sur",
                                                            "ury","ven"],
                        "Northern_America":["bmu","can","grl","spm","usa"],
                        "EU": ["lie","nor", "isl","che",
                            "gbr",
                            "bgr","cze","hun","rou","svk","dnk","est","fin","irl","cyp",
                            "swe","lva","hrv","grc","ita","mlt","prt","svn","esp","aut",
                            "bel","fra","deu","lux","mco","nld"],
                        "Others": ["oth","wcnt","yugo","unde","kos"]
                    
                    }
#32
country_dictEU = {"EU": ["lie","nor", "isl","che",
                        "gbr",
                        "bgr","cze","hun","rou","svk","dnk","est","fin","irl","cyp",
                        "swe","lva","hrv","grc","ita","mlt","prt","svn","esp","aut",
                        "bel","fra","deu","lux","mco","nld"],
                  "pol":["pol"]                    
                    }